wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1652547499
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      4: 3.7.13
      5: 0.12.15
      8:
      - 3
      - 5
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 16
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
cfg:
  desc: null
  value: C:\Users\Dgolberg\workspace\2022-courses\Computer_Vision\final_project\yolov5\models\yolov5s.yaml
cos_lr:
  desc: null
  value: false
data:
  desc: null
  value: C:\Users\Dgolberg\workspace\2022-courses\Computer_Vision\final_project\yolov5\data\data_set.yaml
data_dict:
  desc: null
  value:
    names:
    - boat
    nc: 1
    test: C:\Users\Dgolberg\workspace\2022-courses\Computer_Vision\final_project\yolov5\..\images\test
    train: C:\Users\Dgolberg\workspace\2022-courses\Computer_Vision\final_project\yolov5\..\images\train
    val: C:\Users\Dgolberg\workspace\2022-courses\Computer_Vision\final_project\yolov5\..\images\val
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 5
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value:
  - 24
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    copy_paste: 0.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.01
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 384
label_smoothing:
  desc: null
  value: 0.0
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: yolo_boats_dg
noautoanchor:
  desc: null
  value: false
noplots:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
optimizer:
  desc: null
  value: SGD
patience:
  desc: null
  value: 100
project:
  desc: null
  value: yolov5\runs\train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: yolov5\runs\train\yolo_boats_dg2
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: yolov5s.pt
workers:
  desc: null
  value: 6
